name: Exercice08
version: 0.0.1
author: Marie-Jo Bégin <petite.chikita@gmail.com>
description: Simple model with one many-to-many relationship.
homepage: http://ondart.me/
dependencies:
  unittest: any
